spring:
  application:
    name: sistema_de_clinica
  datasource:
    url: jdbc:mysql://localhost:3306/clinica_db?createDatabaseIfNotExist=true
    username: root
    password: senha123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true